### ISSUE TITLE
Idea: A "skyblock" `HealthBarStyle`

### ISSUE THREAD

**Issue by James103** [samolego/HealthCare#2]
Basically, the `HealthBarStyle.SKYBLOCK` style would format the health portion of the mob as follows:

> 8/20❤

where the "8" (current HP) would be shown in yellow if the mob is at less than or equal to half health or green otherwise, followed by a white slash, followed by the mob's max health in green, followed by a red heart.

Because HP values in vanilla Minecraft rarely ever exceed 1,000 (and most mobs have 100 HP or less), the current HP can be shown to two decimal places, like this:

> 8.25/20❤

The above example in full form would be:

> Zombie 8.25/20❤

A few more examples:

> Horse 25/25❤

> Iron Golem 85/100❤

> Cod 3/3❤

> Wither 298/300❤

**Comment by samolego** [comment]
Thanks for the suggestion! Doesn't sound too hard to implement :)

**Comment by James103** [comment]
A screenshot example of the style that I'm going for with my idea:

![image](https://user-images.githubusercontent.com/37945304/117098893-4b1d1080-ad35-11eb-956b-b19d205291d4.png)

The mob on the left is the half-health example, while the mob on the right is the full-health example. Pay attention to the health counters; ignore the red coloring of the mob's name and the level counter.

**Comment by samolego** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/34912839/117155598-31271080-adbd-11eb-9846-2033fd1da83d.png)
![image](https://user-images.githubusercontent.com/34912839/117155584-2e2c2000-adbd-11eb-9e46-7b7436bf9fa5.png)

**Comment by samolego** [comment]
Fixed the slash & heart icon
![image](https://user-images.githubusercontent.com/34912839/117158888-199d5700-adc0-11eb-84f9-5d0d42e21a59.png)

**Comment by James103** [comment]
That's pretty much exactly what I was looking for.
* Health tag colors match exactly
* Level of precision is correct

**Comment by samolego** [comment]
I guess I can close this then :).

**Comment by James103** [comment]
Do you plan on making a release for this soon so that I can test it out?

**Comment by samolego** [comment]
You can already test it with current sources
